#!/bin/bash

# Settings
# executable path on distant host
town_exec=~/prisoners-dilemma/town
# options
n_hosts=5
town_options[1]='-p 100'
town_options[2]='-p 30 -d m,ddd,pm,mm'
town_options[3]='-d all -a g,m,dd -p g:10 -p m,dd:30'
town_options[4]='-p 10 -p m,pm,s,mf:100'
town_options[5]='-p 100'
for host in $(seq 1 ${n_hosts}); do
    host_name[host]=$(printf "%.2d.dptinfo.ens-cachan.fr" "${host}")
done
# monitoring port
mon_port=4000


mon_args=
for host in $(seq 1 ${n_hosts}); do
    mon_args="${mon_args} ${host_name[host]}:${mon_port}"
    ssh "${host_name[host]}" "${town_exec} ${town_options[host]} -m ${mon_port}" &
done
./monitor ${mon_args}
