#!/bin/bash

# Settings
# executable path on distant host
town_exec=~/prisoners-dilemma/town
# options
town_options='-p 100'
# monitoring port
mon_port=4000
con_port=4001


mon_args=
for host in {1..23}; do
    host_name[host]=$(printf "%.2d.dptinfo.ens-cachan.fr" "${host}")
    mon_args="${mon_args} ${host_name[host]}:${mon_port}"
done

for host in {1..23}; do
    # create the list of neighbours with -o option
    neighbours=
    for i in {1..23}; do
        if [[ i == host ]]; then
            neighbours="${neighbours} -o ${host_name[i]}:${con_port}"
        fi
    done
    # launch town simulations
    options="${town_options} -m ${mon_port} -i ${con_port} ${neighbours}"
    ssh "${host_name[host]}" "${town_exec} ${options}" &
done
# launch monitoring
./monitor ${mon_args}
